name: Unit Tests
on: push
jobs:
  go-tests:
    name: Run Go Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - uses:  hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.5
          terraform_wrapper: false  
      - uses: FranzDiebold/github-env-vars-action@v2
      - uses: archive/github-actions-slack@v1.1.0
      - name: Git Message
        id: notify
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_TOKEN }}  
          slack-channel: random
          slack-text: Lee's "${{ github.event_name }}"ing a big hard CI test, and he's doing it from this "${{ github.repository }}" repo ... Duck you!   
      - name: Download Go Modules
        run: go mod download
      - name: Run Go Tests
        working-directory: test
        run: go test -test.timeout 0 -v -identifier $CI_SHA_SHORT 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Result from "Send Message"
        run: echo "The result was ${{ steps.notify.outputs.slack-result }}"
          
