name: Unit Tests
on: push
jobs:
  go-tests:
    name: Run Go Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - uses:  hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.5
      - name: Download Go Modules
        run: go mod download
      - name: Run Go Tests
        working-directory: test
        run: go test ./test -test.timeout 0 -v -identifier CI_SHA_SHORT
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
